name: API Automation Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:

  api-tests:

    runs-on: ubuntu-latest

    services:

      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181

      kafka:
        image: confluentinc/cp-kafka:latest

        ports:
          - 9092:9092

        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Wait for Kafka

        run: |

          sleep 40

      - name: Run Tests

        env:

          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}

          PYTHONPATH: .

        run: |
             export PYTHONPATH=.

              pytest \
               -v \
                 -s \
                 --tb=long