name: API Tests

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    services:

      zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0

        env:
          ZOOKEEPER_CLIENT_PORT: 2181

        ports:
          - 2181:2181

      kafka:
        image: confluentinc/cp-kafka:7.6.0

        env:
          KAFKA_BROKER_ID: 1

          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

          KAFKA_LISTENERS: PLAINTEXT://:9092

          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

        ports:
          - 9092:9092

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:
          python-version: "3.13"

      - name: Install dependencies

        run: |

          pip install --upgrade pip

          pip install -r requirements.txt

      - name: Wait for Kafka

        run: |

          sleep 40

      - name: Set env

        run: |

          echo "REQRES_API_KEY=${{ secrets.REQRES_API_KEY }}" >> $GITHUB_ENV
          echo "KAFKA_BOOTSTRAP_SERVERS=kafka:9092" >> $GITHUB_ENV

      - name: Run tests

        env:

          PYTHONPATH: .

          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}

          KAFKA_BOOTSTRAP_SERVERS: kafka:9092

        run: |

          pytest -v -s